-- 实时策略表建表语句
CREATE TABLE IF NOT EXISTS `real_time_strategy` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT '自增主键ID',
  `strategy_code` VARCHAR(50) NOT NULL UNIQUE COMMENT '实时策略唯一代码',
  `strategy_info_code` VARCHAR(50) NOT NULL COMMENT '关联的策略信息代码',
  `symbol` VARCHAR(20) NOT NULL COMMENT '交易对符号，如BTC-USDT',
  `interval_val` VARCHAR(10) NOT NULL COMMENT 'K线周期，如1m, 5m, 1h等',
  `start_time` DATETIME NOT NULL COMMENT '策略运行开始时间',
  `end_time` DATETIME COMMENT '策略运行结束时间',
  `is_active` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否有效/启用',
  `is_simulated` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否为模拟交易',
  `order_type` VARCHAR(10) DEFAULT 'market' COMMENT '订单类型：market(市价), limit(限价)',
  `trade_amount` DOUBLE COMMENT '交易金额',
  `status` VARCHAR(20) DEFAULT 'STOPPED' COMMENT '策略运行状态：RUNNING(运行中), STOPPED(已停止), COMPLETED(已完成), ERROR(错误)',
  `description` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '策略描述',
  `error_message` TEXT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '错误信息',
  `create_time` DATETIME NOT NULL COMMENT '创建时间',
  `update_time` DATETIME NOT NULL COMMENT '更新时间',
  INDEX `idx_strategy_code` (`strategy_code`),
  INDEX `idx_strategy_info_code` (`strategy_info_code`),
  INDEX `idx_symbol` (`symbol`),
  INDEX `idx_status` (`status`),
  INDEX `idx_is_active` (`is_active`),
  INDEX `idx_create_time` (`create_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='实时运行策略表';
